geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admin-staff/', include('admins.urls', namespace='admins')),
    path('', include('social_django.urls', namespace='social')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from orders.views import OrderListView, OrderCreateView, OrderDeleteView, OrderUpdateView, OrderDetailView, order_forming_complete

app_name = 'orders'

urlpatterns = [
    path('', OrderListView.as_view(), name='list'),
    path('create/', OrderCreateView.as_view(), name='create'),
    path('update/<int:pk>/', OrderUpdateView.as_view(), name='update'),
    path('read/<int:pk>/', OrderDetailView.as_view(), name='read'),
    path('delete/<int:pk>/', OrderDeleteView.as_view(), name='delete'),
    path('order_complete/<int:pk>/', order_forming_complete, name='order_complete'),
    ]

users/urls.py
from django.urls import path

from users.views import UserLoginView, UserRegistrationView, UserLogoutView, UserProfileView
from django.contrib.auth.decorators import login_required

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<str:activation_key>/', UserRegistrationView.verify, name='verify'),
]

orders/models.py
from django.conf import settings
from django.db import models
from products.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='обновлен', auto_now=True)
    status = models.CharField(verbose_name='статус', max_length=3, choices=ORDER_STATUS_CHOICES, default=FORMING)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    def __str__(self):
        return f'Текущий заказ: {self.pk}'

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.get_product_cost(), items)))

    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()

        self.is_active = False
        self.save()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, verbose_name='заказ', related_name="orderitems", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='продукт', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.get(pk=pk).quantity

orders/forms.py
from django import forms
from orders.models import Order, OrderItem


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label='цена', required=False)

    class Meta:
        model = OrderItem
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

orders/views.py
from django.db import transaction
from django.db.models.signals import pre_save, pre_delete
from django.dispatch import receiver
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DeleteView, DetailView, UpdateView, CreateView

from baskets.models import Basket
from orders.forms import OrderItemForm
from orders.models import Order, OrderItem


class OrderListView(ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user, is_active=True)


class OrderCreateView(CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('orders:list')

    def get_context_data(self, **kwargs):
        context = super(OrderCreateView, self).get_context_data(**kwargs)

        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)
        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            basket_item = Basket.objects.filter(user=self.request.user)
            if basket_item:
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=basket_item.count())
                formset = OrderFormSet()
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_item[num].product
                    form.initial['quantity'] = basket_item[num].quantity
                    form.initial['price'] = basket_item[num].product.price
                basket_item.delete()
            else:
                formset = OrderFormSet()
        context['orderitems'] = formset
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

            if self.object.get_total_cost() == 0:
                self.object.delete()
        return super(OrderCreateView, self).form_valid(form)


class OrderUpdateView(UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('orders:list')

    def get_context_data(self, **kwargs):
        context = super(OrderUpdateView, self).get_context_data(**kwargs)

        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)
        if self.request.POST:
            formset = OrderFormSet(self.request.POST, instance=self.object)
        else:
            formset = OrderFormSet(instance=self.object)
            for form in formset:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price

        context['orderitems'] = formset
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

            if self.object.get_total_cost() == 0:
                self.object.delete()
        return super(OrderUpdateView, self).form_valid(form)


class OrderDetailView(DetailView):
    model = Order


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy('orders:list')


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()
    return HttpResponseRedirect(reverse('orders:list'))


@receiver(pre_save, sender=OrderItem)
@receiver(pre_save, sender=Basket)
def product_quantity_update_save(sender, instance, **kwargs):
    if instance.pk:
        instance.product.quantity -= instance.quantity - instance.get_item(int(instance.pk))
    else:
        instance.product.quantity -= instance.quantity
    instance.product.save()


@receiver(pre_delete, sender=OrderItem)
@receiver(pre_delete, sender=Basket)
def product_quantity_update_delete(sender, instance, **kwargs):
    instance.product.quantity += instance.quantity
    instance.product.save()

orders/templates/orders/order_confirm_delete.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}
    <div class="text-center">
        <div>
            <div class="h1">Уверены, что хотите удалить?</div>
                {% include 'orders/includes/inc_order_summary.html' %}
                <form action="{% url 'orders:delete' object.pk %}" method="post">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-danger" value="удалить">
                </form>
                <button class="btn btn-success mt-4">
                    <a href="{% url 'orders:list' %}">отмена</a>
                </button>
        </div>
    </div>
{% endblock %}

orders/templates/orders/order_detail.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}
    {% include 'orders/includes/inc_order_summary.html' %}
    <div class="basket_list">
        {% for item in object.orderitems.select_related %}
            <div>
                <img style="height: 150px" src="{{ item.product.image.url }}" alt="{{ item.product.short_desc }}">
                <span class="category_name">{{ item.product.category.name }}</span>
                <span class="product_name">{{ item.product.name }}</span>
                <span class="product_price">{{ item.product.price }} руб</span>
                <span class="product_quantity">{{ item.quantity }} шт</span>
                <span class="product_cost">{{ item.get_total_cost }} руб</span>
            </div>
        {% endfor %}
    </div>
    {% include 'orders/includes/inc_order_actions.html' %}
{% endblock %}

orders/templates/orders/order_form.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}
    {% include 'orders/includes/inc_order_summary.html' %}
    <div class="order_form">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <table class="table">
                {{ orderitems.management_form }}
                {% for form in orderitems.forms %}
                    {% if forloop.first %}
                        <thead>
                            <tr>
                                {% for field in form.visible_fields %}
                                    <th class="{% cycle 'td1' 'td2' 'td3' %} order formset_td">
                                        {{ field.label }}
                                    </th>
                                {% endfor %}
                            </tr>
                        </thead>
                    {% endif %}
                    <tr class="formset_row">
                        {% for field in form.visible_fields %}
                            <td class="{% cycle 'td1' 'td2' 'td3' %} order formset_td">
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {% if field.name == 'price' %}
                                    {% if not field.value %}
                                    {% else %}
                                        <span class="orderitems-{{ forloop.parentloop.counter0 }}-price">{{ field.value }} руб</span>
                                    {% endif %}
                                {% else %}
                                    {{ field }}
                                {% endif %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            <button type="submit" value="сохранить" class="btn btn-default btn-round form-control last">
                сохранить
            </button>
            {% include 'orders/includes/inc_order_actions.html' %}
        </form>
    </div>
{% endblock %}

orders/templates/orders/order_list.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}
    <div class="text-center">
        <div class="h2 text-center head">
            Ваши заказы,
            {% if user.first_name %}
                {{ user.first_name }}
            {% else %}
                Пользователь
            {% endif %}
        </div>
        <div class="orders mt-5">
            <tbody class="table">
                <thead>
                <tr class="table-light">
                    <th scope="col">ID</th>
                    <th scope="col">Статус</th>
                    <th scope="col">Создан</th>
                    <th scope="col">Обновлен</th>
                </tr>
                </thead>
                <tbody>
                {% for item in object_list %}
                    {% if item.is_active %}
                        <tr>
                            <td class="td1 orders_list">{{ item.pk }}</td>
                            <td>{{ item.get_status_display }}</td>
                            <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                            <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                            <td>
                                <a href="{% url 'orders:read' item.pk %}">просмотреть</a>
                            </td>
                            <td>
                                {% if item.status == 'FM' %}
                                <a href="{% url 'orders:update' item.pk %}">
                                    Редактировать
                                </a>
                                {% endif %}
                            </td>
                            <td>
                                {% if item.status == 'FM' %}
                                <a href="{% url 'orders:delete' item.pk %}">
                                    Удалить
                                </a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
        <button class="btn btn-light bg-round">
            <a href="{% url 'index' %}">на главную</a>
        </button>
        <button class="btn btn-warning bg-round">
            <a href="{% url 'orders:create' %}">новый заказ</a>
        </button>
    </div>
{% endblock %}